export const CREATE_MENTAL_STATS = "CREATE_MENTAL_STATS";
export const LOAD_MENTAL_STATS_SUCCESS = "LOAD_MENTAL_STATS_SUCCESS";
export const CREATE_MENTAL_STATS_SUCCESS = "CREATE_MENTAL_STATS_SUCCESS";
export const UPDATE_MENTAL_STATS_SUCCESS = "UPDATE_MENTAL_STATS_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_MENTAL_STATS_OPTIMISTIC = "DELETE_MENTAL_STATS_OPTIMISTIC";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
